[package]
name = "tui-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.26.1"
message-io = "0.15.0"
serde = { version = "1.0.159", features = ["derive"] }
tui = "0.19.0"
